#---Vagrant COnfiguration---#

Vagrant.configure("2") do |config|
  config.vm.box = "centos/8" # vagrant image
  config.vm.hostname = "dev-infra-vm" # vm's name
  config.vm.network "private_network", ip: "192.168.56.5" # static LAN IP within same subnet
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "6144"
    vb.cpus = "2"
  end
end
